const numberA = prompt("Enter the first number a");
const numberB = prompt("Enter the second number b");
const sum = (Number(numberA) + Number(numberB))
const subtraction = (Number(numberA) - Number(numberB))
const multiplication = (Number(numberA) * Number(numberB))
const division = (Number(numberA) / Number(numberB))
alert(numberA + '+' + numberB + '=' + sum + ';' + "\n"
    + numberA + '-' + numberB + '=' + subtraction + ';' + "\n"
    + numberA + '*' + numberB + '=' + multiplication + ';' + "\n"
    + numberA + '/' + numberB + '=' + division + ';')
